### ISSUE TITLE
Does it support the invisible mode 

### ISSUE THREAD

**Issue by DanielTal** [alexd1971/angular_grecaptcha#1]
We tried by the 
size="invisible" 
attribute on the   g-recaptcha tag
and it renders ok 
but then we miss a mechanism to invoke the grecaptcha.execute(); method

**Comment by alexd1971** [comment]
Thank you! This is because I did not plan to use invisible reCaptcha. But I will try to extend the functionality.

**Comment by alexd1971** [comment]
Added support for execute()

**Comment by DanielTal** [comment]
Hello Alex, 
works great. thanks very much.
